// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package proto_generated;

public final class ThreadManagement {
  private ThreadManagement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestByIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_generated.SearchRequestById)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageId = 1;</code>
     */
    int getMessageId();
  }
  /**
   * Protobuf type {@code proto_generated.SearchRequestById}
   */
  public  static final class SearchRequestById extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_generated.SearchRequestById)
      SearchRequestByIdOrBuilder {
    // Use SearchRequestById.newBuilder() to construct.
    private SearchRequestById(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequestById() {
      messageId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SearchRequestById(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_SearchRequestById_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_SearchRequestById_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_generated.ThreadManagement.SearchRequestById.class, proto_generated.ThreadManagement.SearchRequestById.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>int32 messageId = 1;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_generated.ThreadManagement.SearchRequestById)) {
        return super.equals(obj);
      }
      proto_generated.ThreadManagement.SearchRequestById other = (proto_generated.ThreadManagement.SearchRequestById) obj;

      boolean result = true;
      result = result && (getMessageId()
          == other.getMessageId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.SearchRequestById parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_generated.ThreadManagement.SearchRequestById prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_generated.SearchRequestById}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_generated.SearchRequestById)
        proto_generated.ThreadManagement.SearchRequestByIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_SearchRequestById_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_SearchRequestById_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_generated.ThreadManagement.SearchRequestById.class, proto_generated.ThreadManagement.SearchRequestById.Builder.class);
      }

      // Construct using proto_generated.ThreadManagement.SearchRequestById.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_SearchRequestById_descriptor;
      }

      public proto_generated.ThreadManagement.SearchRequestById getDefaultInstanceForType() {
        return proto_generated.ThreadManagement.SearchRequestById.getDefaultInstance();
      }

      public proto_generated.ThreadManagement.SearchRequestById build() {
        proto_generated.ThreadManagement.SearchRequestById result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto_generated.ThreadManagement.SearchRequestById buildPartial() {
        proto_generated.ThreadManagement.SearchRequestById result = new proto_generated.ThreadManagement.SearchRequestById(this);
        result.messageId_ = messageId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_generated.ThreadManagement.SearchRequestById) {
          return mergeFrom((proto_generated.ThreadManagement.SearchRequestById)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_generated.ThreadManagement.SearchRequestById other) {
        if (other == proto_generated.ThreadManagement.SearchRequestById.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_generated.ThreadManagement.SearchRequestById parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_generated.ThreadManagement.SearchRequestById) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <code>int32 messageId = 1;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 1;</code>
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto_generated.SearchRequestById)
    }

    // @@protoc_insertion_point(class_scope:proto_generated.SearchRequestById)
    private static final proto_generated.ThreadManagement.SearchRequestById DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_generated.ThreadManagement.SearchRequestById();
    }

    public static proto_generated.ThreadManagement.SearchRequestById getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequestById>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequestById>() {
      public SearchRequestById parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchRequestById(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequestById> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequestById> getParserForType() {
      return PARSER;
    }

    public proto_generated.ThreadManagement.SearchRequestById getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ThreadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_generated.Thread)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string text = 3;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 3;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code proto_generated.Thread}
   */
  public  static final class Thread extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_generated.Thread)
      ThreadOrBuilder {
    // Use Thread.newBuilder() to construct.
    private Thread(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Thread() {
      id_ = 0;
      title_ = "";
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Thread(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_Thread_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_Thread_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_generated.ThreadManagement.Thread.class, proto_generated.ThreadManagement.Thread.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 3;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, text_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, text_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_generated.ThreadManagement.Thread)) {
        return super.equals(obj);
      }
      proto_generated.ThreadManagement.Thread other = (proto_generated.ThreadManagement.Thread) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getText()
          .equals(other.getText());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_generated.ThreadManagement.Thread parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.Thread parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.Thread parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.Thread parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.Thread parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.Thread parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.Thread parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.Thread parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.Thread parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.Thread parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_generated.ThreadManagement.Thread prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_generated.Thread}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_generated.Thread)
        proto_generated.ThreadManagement.ThreadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_Thread_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_Thread_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_generated.ThreadManagement.Thread.class, proto_generated.ThreadManagement.Thread.Builder.class);
      }

      // Construct using proto_generated.ThreadManagement.Thread.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        text_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_Thread_descriptor;
      }

      public proto_generated.ThreadManagement.Thread getDefaultInstanceForType() {
        return proto_generated.ThreadManagement.Thread.getDefaultInstance();
      }

      public proto_generated.ThreadManagement.Thread build() {
        proto_generated.ThreadManagement.Thread result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto_generated.ThreadManagement.Thread buildPartial() {
        proto_generated.ThreadManagement.Thread result = new proto_generated.ThreadManagement.Thread(this);
        result.id_ = id_;
        result.title_ = title_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_generated.ThreadManagement.Thread) {
          return mergeFrom((proto_generated.ThreadManagement.Thread)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_generated.ThreadManagement.Thread other) {
        if (other == proto_generated.ThreadManagement.Thread.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_generated.ThreadManagement.Thread parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_generated.ThreadManagement.Thread) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 3;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 3;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 3;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 3;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto_generated.Thread)
    }

    // @@protoc_insertion_point(class_scope:proto_generated.Thread)
    private static final proto_generated.ThreadManagement.Thread DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_generated.ThreadManagement.Thread();
    }

    public static proto_generated.ThreadManagement.Thread getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Thread>
        PARSER = new com.google.protobuf.AbstractParser<Thread>() {
      public Thread parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Thread(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Thread> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Thread> getParserForType() {
      return PARSER;
    }

    public proto_generated.ThreadManagement.Thread getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_generated.CreateReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto_generated.Thread thread = 1;</code>
     */
    boolean hasThread();
    /**
     * <code>.proto_generated.Thread thread = 1;</code>
     */
    proto_generated.ThreadManagement.Thread getThread();
    /**
     * <code>.proto_generated.Thread thread = 1;</code>
     */
    proto_generated.ThreadManagement.ThreadOrBuilder getThreadOrBuilder();
  }
  /**
   * Protobuf type {@code proto_generated.CreateReply}
   */
  public  static final class CreateReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_generated.CreateReply)
      CreateReplyOrBuilder {
    // Use CreateReply.newBuilder() to construct.
    private CreateReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateReply() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CreateReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto_generated.ThreadManagement.Thread.Builder subBuilder = null;
              if (thread_ != null) {
                subBuilder = thread_.toBuilder();
              }
              thread_ = input.readMessage(proto_generated.ThreadManagement.Thread.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(thread_);
                thread_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_CreateReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_CreateReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_generated.ThreadManagement.CreateReply.class, proto_generated.ThreadManagement.CreateReply.Builder.class);
    }

    public static final int THREAD_FIELD_NUMBER = 1;
    private proto_generated.ThreadManagement.Thread thread_;
    /**
     * <code>.proto_generated.Thread thread = 1;</code>
     */
    public boolean hasThread() {
      return thread_ != null;
    }
    /**
     * <code>.proto_generated.Thread thread = 1;</code>
     */
    public proto_generated.ThreadManagement.Thread getThread() {
      return thread_ == null ? proto_generated.ThreadManagement.Thread.getDefaultInstance() : thread_;
    }
    /**
     * <code>.proto_generated.Thread thread = 1;</code>
     */
    public proto_generated.ThreadManagement.ThreadOrBuilder getThreadOrBuilder() {
      return getThread();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (thread_ != null) {
        output.writeMessage(1, getThread());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (thread_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getThread());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_generated.ThreadManagement.CreateReply)) {
        return super.equals(obj);
      }
      proto_generated.ThreadManagement.CreateReply other = (proto_generated.ThreadManagement.CreateReply) obj;

      boolean result = true;
      result = result && (hasThread() == other.hasThread());
      if (hasThread()) {
        result = result && getThread()
            .equals(other.getThread());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasThread()) {
        hash = (37 * hash) + THREAD_FIELD_NUMBER;
        hash = (53 * hash) + getThread().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_generated.ThreadManagement.CreateReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.CreateReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.CreateReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.CreateReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.CreateReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.CreateReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.CreateReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.CreateReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.CreateReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.CreateReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_generated.ThreadManagement.CreateReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_generated.CreateReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_generated.CreateReply)
        proto_generated.ThreadManagement.CreateReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_CreateReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_CreateReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_generated.ThreadManagement.CreateReply.class, proto_generated.ThreadManagement.CreateReply.Builder.class);
      }

      // Construct using proto_generated.ThreadManagement.CreateReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (threadBuilder_ == null) {
          thread_ = null;
        } else {
          thread_ = null;
          threadBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_CreateReply_descriptor;
      }

      public proto_generated.ThreadManagement.CreateReply getDefaultInstanceForType() {
        return proto_generated.ThreadManagement.CreateReply.getDefaultInstance();
      }

      public proto_generated.ThreadManagement.CreateReply build() {
        proto_generated.ThreadManagement.CreateReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto_generated.ThreadManagement.CreateReply buildPartial() {
        proto_generated.ThreadManagement.CreateReply result = new proto_generated.ThreadManagement.CreateReply(this);
        if (threadBuilder_ == null) {
          result.thread_ = thread_;
        } else {
          result.thread_ = threadBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_generated.ThreadManagement.CreateReply) {
          return mergeFrom((proto_generated.ThreadManagement.CreateReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_generated.ThreadManagement.CreateReply other) {
        if (other == proto_generated.ThreadManagement.CreateReply.getDefaultInstance()) return this;
        if (other.hasThread()) {
          mergeThread(other.getThread());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_generated.ThreadManagement.CreateReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_generated.ThreadManagement.CreateReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto_generated.ThreadManagement.Thread thread_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto_generated.ThreadManagement.Thread, proto_generated.ThreadManagement.Thread.Builder, proto_generated.ThreadManagement.ThreadOrBuilder> threadBuilder_;
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public boolean hasThread() {
        return threadBuilder_ != null || thread_ != null;
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.Thread getThread() {
        if (threadBuilder_ == null) {
          return thread_ == null ? proto_generated.ThreadManagement.Thread.getDefaultInstance() : thread_;
        } else {
          return threadBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public Builder setThread(proto_generated.ThreadManagement.Thread value) {
        if (threadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          thread_ = value;
          onChanged();
        } else {
          threadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public Builder setThread(
          proto_generated.ThreadManagement.Thread.Builder builderForValue) {
        if (threadBuilder_ == null) {
          thread_ = builderForValue.build();
          onChanged();
        } else {
          threadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public Builder mergeThread(proto_generated.ThreadManagement.Thread value) {
        if (threadBuilder_ == null) {
          if (thread_ != null) {
            thread_ =
              proto_generated.ThreadManagement.Thread.newBuilder(thread_).mergeFrom(value).buildPartial();
          } else {
            thread_ = value;
          }
          onChanged();
        } else {
          threadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public Builder clearThread() {
        if (threadBuilder_ == null) {
          thread_ = null;
          onChanged();
        } else {
          thread_ = null;
          threadBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.Thread.Builder getThreadBuilder() {
        
        onChanged();
        return getThreadFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.ThreadOrBuilder getThreadOrBuilder() {
        if (threadBuilder_ != null) {
          return threadBuilder_.getMessageOrBuilder();
        } else {
          return thread_ == null ?
              proto_generated.ThreadManagement.Thread.getDefaultInstance() : thread_;
        }
      }
      /**
       * <code>.proto_generated.Thread thread = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto_generated.ThreadManagement.Thread, proto_generated.ThreadManagement.Thread.Builder, proto_generated.ThreadManagement.ThreadOrBuilder> 
          getThreadFieldBuilder() {
        if (threadBuilder_ == null) {
          threadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto_generated.ThreadManagement.Thread, proto_generated.ThreadManagement.Thread.Builder, proto_generated.ThreadManagement.ThreadOrBuilder>(
                  getThread(),
                  getParentForChildren(),
                  isClean());
          thread_ = null;
        }
        return threadBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto_generated.CreateReply)
    }

    // @@protoc_insertion_point(class_scope:proto_generated.CreateReply)
    private static final proto_generated.ThreadManagement.CreateReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_generated.ThreadManagement.CreateReply();
    }

    public static proto_generated.ThreadManagement.CreateReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateReply>
        PARSER = new com.google.protobuf.AbstractParser<CreateReply>() {
      public CreateReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CreateReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateReply> getParserForType() {
      return PARSER;
    }

    public proto_generated.ThreadManagement.CreateReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_generated.SearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    java.util.List<proto_generated.ThreadManagement.Thread> 
        getThreadList();
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    proto_generated.ThreadManagement.Thread getThread(int index);
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    int getThreadCount();
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    java.util.List<? extends proto_generated.ThreadManagement.ThreadOrBuilder> 
        getThreadOrBuilderList();
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    proto_generated.ThreadManagement.ThreadOrBuilder getThreadOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto_generated.SearchResponse}
   */
  public  static final class SearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_generated.SearchResponse)
      SearchResponseOrBuilder {
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResponse() {
      thread_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                thread_ = new java.util.ArrayList<proto_generated.ThreadManagement.Thread>();
                mutable_bitField0_ |= 0x00000001;
              }
              thread_.add(
                  input.readMessage(proto_generated.ThreadManagement.Thread.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          thread_ = java.util.Collections.unmodifiableList(thread_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_SearchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_generated.ThreadManagement.internal_static_proto_generated_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_generated.ThreadManagement.SearchResponse.class, proto_generated.ThreadManagement.SearchResponse.Builder.class);
    }

    public static final int THREAD_FIELD_NUMBER = 1;
    private java.util.List<proto_generated.ThreadManagement.Thread> thread_;
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    public java.util.List<proto_generated.ThreadManagement.Thread> getThreadList() {
      return thread_;
    }
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    public java.util.List<? extends proto_generated.ThreadManagement.ThreadOrBuilder> 
        getThreadOrBuilderList() {
      return thread_;
    }
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    public int getThreadCount() {
      return thread_.size();
    }
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    public proto_generated.ThreadManagement.Thread getThread(int index) {
      return thread_.get(index);
    }
    /**
     * <code>repeated .proto_generated.Thread thread = 1;</code>
     */
    public proto_generated.ThreadManagement.ThreadOrBuilder getThreadOrBuilder(
        int index) {
      return thread_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < thread_.size(); i++) {
        output.writeMessage(1, thread_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < thread_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, thread_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_generated.ThreadManagement.SearchResponse)) {
        return super.equals(obj);
      }
      proto_generated.ThreadManagement.SearchResponse other = (proto_generated.ThreadManagement.SearchResponse) obj;

      boolean result = true;
      result = result && getThreadList()
          .equals(other.getThreadList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getThreadCount() > 0) {
        hash = (37 * hash) + THREAD_FIELD_NUMBER;
        hash = (53 * hash) + getThreadList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_generated.ThreadManagement.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_generated.ThreadManagement.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_generated.ThreadManagement.SearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_generated.SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_generated.SearchResponse)
        proto_generated.ThreadManagement.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_SearchResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_generated.ThreadManagement.SearchResponse.class, proto_generated.ThreadManagement.SearchResponse.Builder.class);
      }

      // Construct using proto_generated.ThreadManagement.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getThreadFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (threadBuilder_ == null) {
          thread_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          threadBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto_generated.ThreadManagement.internal_static_proto_generated_SearchResponse_descriptor;
      }

      public proto_generated.ThreadManagement.SearchResponse getDefaultInstanceForType() {
        return proto_generated.ThreadManagement.SearchResponse.getDefaultInstance();
      }

      public proto_generated.ThreadManagement.SearchResponse build() {
        proto_generated.ThreadManagement.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto_generated.ThreadManagement.SearchResponse buildPartial() {
        proto_generated.ThreadManagement.SearchResponse result = new proto_generated.ThreadManagement.SearchResponse(this);
        int from_bitField0_ = bitField0_;
        if (threadBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            thread_ = java.util.Collections.unmodifiableList(thread_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.thread_ = thread_;
        } else {
          result.thread_ = threadBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_generated.ThreadManagement.SearchResponse) {
          return mergeFrom((proto_generated.ThreadManagement.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_generated.ThreadManagement.SearchResponse other) {
        if (other == proto_generated.ThreadManagement.SearchResponse.getDefaultInstance()) return this;
        if (threadBuilder_ == null) {
          if (!other.thread_.isEmpty()) {
            if (thread_.isEmpty()) {
              thread_ = other.thread_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureThreadIsMutable();
              thread_.addAll(other.thread_);
            }
            onChanged();
          }
        } else {
          if (!other.thread_.isEmpty()) {
            if (threadBuilder_.isEmpty()) {
              threadBuilder_.dispose();
              threadBuilder_ = null;
              thread_ = other.thread_;
              bitField0_ = (bitField0_ & ~0x00000001);
              threadBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getThreadFieldBuilder() : null;
            } else {
              threadBuilder_.addAllMessages(other.thread_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_generated.ThreadManagement.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_generated.ThreadManagement.SearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto_generated.ThreadManagement.Thread> thread_ =
        java.util.Collections.emptyList();
      private void ensureThreadIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          thread_ = new java.util.ArrayList<proto_generated.ThreadManagement.Thread>(thread_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto_generated.ThreadManagement.Thread, proto_generated.ThreadManagement.Thread.Builder, proto_generated.ThreadManagement.ThreadOrBuilder> threadBuilder_;

      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public java.util.List<proto_generated.ThreadManagement.Thread> getThreadList() {
        if (threadBuilder_ == null) {
          return java.util.Collections.unmodifiableList(thread_);
        } else {
          return threadBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public int getThreadCount() {
        if (threadBuilder_ == null) {
          return thread_.size();
        } else {
          return threadBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.Thread getThread(int index) {
        if (threadBuilder_ == null) {
          return thread_.get(index);
        } else {
          return threadBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder setThread(
          int index, proto_generated.ThreadManagement.Thread value) {
        if (threadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThreadIsMutable();
          thread_.set(index, value);
          onChanged();
        } else {
          threadBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder setThread(
          int index, proto_generated.ThreadManagement.Thread.Builder builderForValue) {
        if (threadBuilder_ == null) {
          ensureThreadIsMutable();
          thread_.set(index, builderForValue.build());
          onChanged();
        } else {
          threadBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder addThread(proto_generated.ThreadManagement.Thread value) {
        if (threadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThreadIsMutable();
          thread_.add(value);
          onChanged();
        } else {
          threadBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder addThread(
          int index, proto_generated.ThreadManagement.Thread value) {
        if (threadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThreadIsMutable();
          thread_.add(index, value);
          onChanged();
        } else {
          threadBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder addThread(
          proto_generated.ThreadManagement.Thread.Builder builderForValue) {
        if (threadBuilder_ == null) {
          ensureThreadIsMutable();
          thread_.add(builderForValue.build());
          onChanged();
        } else {
          threadBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder addThread(
          int index, proto_generated.ThreadManagement.Thread.Builder builderForValue) {
        if (threadBuilder_ == null) {
          ensureThreadIsMutable();
          thread_.add(index, builderForValue.build());
          onChanged();
        } else {
          threadBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder addAllThread(
          java.lang.Iterable<? extends proto_generated.ThreadManagement.Thread> values) {
        if (threadBuilder_ == null) {
          ensureThreadIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, thread_);
          onChanged();
        } else {
          threadBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder clearThread() {
        if (threadBuilder_ == null) {
          thread_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          threadBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public Builder removeThread(int index) {
        if (threadBuilder_ == null) {
          ensureThreadIsMutable();
          thread_.remove(index);
          onChanged();
        } else {
          threadBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.Thread.Builder getThreadBuilder(
          int index) {
        return getThreadFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.ThreadOrBuilder getThreadOrBuilder(
          int index) {
        if (threadBuilder_ == null) {
          return thread_.get(index);  } else {
          return threadBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public java.util.List<? extends proto_generated.ThreadManagement.ThreadOrBuilder> 
           getThreadOrBuilderList() {
        if (threadBuilder_ != null) {
          return threadBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(thread_);
        }
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.Thread.Builder addThreadBuilder() {
        return getThreadFieldBuilder().addBuilder(
            proto_generated.ThreadManagement.Thread.getDefaultInstance());
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public proto_generated.ThreadManagement.Thread.Builder addThreadBuilder(
          int index) {
        return getThreadFieldBuilder().addBuilder(
            index, proto_generated.ThreadManagement.Thread.getDefaultInstance());
      }
      /**
       * <code>repeated .proto_generated.Thread thread = 1;</code>
       */
      public java.util.List<proto_generated.ThreadManagement.Thread.Builder> 
           getThreadBuilderList() {
        return getThreadFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto_generated.ThreadManagement.Thread, proto_generated.ThreadManagement.Thread.Builder, proto_generated.ThreadManagement.ThreadOrBuilder> 
          getThreadFieldBuilder() {
        if (threadBuilder_ == null) {
          threadBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto_generated.ThreadManagement.Thread, proto_generated.ThreadManagement.Thread.Builder, proto_generated.ThreadManagement.ThreadOrBuilder>(
                  thread_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          thread_ = null;
        }
        return threadBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto_generated.SearchResponse)
    }

    // @@protoc_insertion_point(class_scope:proto_generated.SearchResponse)
    private static final proto_generated.ThreadManagement.SearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_generated.ThreadManagement.SearchResponse();
    }

    public static proto_generated.ThreadManagement.SearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    public proto_generated.ThreadManagement.SearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_generated_SearchRequestById_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_generated_SearchRequestById_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_generated_Thread_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_generated_Thread_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_generated_CreateReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_generated_CreateReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_generated_SearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_generated_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\017proto_generated\"&\n\021Sear" +
      "chRequestById\022\021\n\tmessageId\030\001 \001(\005\"1\n\006Thre" +
      "ad\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\014\n\004text\030\003 " +
      "\001(\t\"6\n\013CreateReply\022\'\n\006thread\030\001 \001(\0132\027.pro" +
      "to_generated.Thread\"9\n\016SearchResponse\022\'\n" +
      "\006thread\030\001 \003(\0132\027.proto_generated.Thread2\205" +
      "\002\n\027ThreadManagementService\022G\n\014createThre" +
      "ad\022\027.proto_generated.Thread\032\034.proto_gene" +
      "rated.CreateReply\"\000\022O\n\006search\022\".proto_ge" +
      "nerated.SearchRequestById\032\037.proto_genera",
      "ted.SearchResponse\"\000\022P\n\007listAll\022\".proto_" +
      "generated.SearchRequestById\032\037.proto_gene" +
      "rated.SearchResponse\"\000B#\n\017proto_generate" +
      "dB\020ThreadManagementb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_generated_SearchRequestById_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_generated_SearchRequestById_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_generated_SearchRequestById_descriptor,
        new java.lang.String[] { "MessageId", });
    internal_static_proto_generated_Thread_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_generated_Thread_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_generated_Thread_descriptor,
        new java.lang.String[] { "Id", "Title", "Text", });
    internal_static_proto_generated_CreateReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_generated_CreateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_generated_CreateReply_descriptor,
        new java.lang.String[] { "Thread", });
    internal_static_proto_generated_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_generated_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_generated_SearchResponse_descriptor,
        new java.lang.String[] { "Thread", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
